# Generated by Django 4.2.6 on 2024-01-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Rate',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
