# Generated by Django 4.2.6 on 2024-01-10 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_property_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='property',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='apartments', serialize=False, to='sellerapp.property'),
        ),
        migrations.AddField(
            model_name='house',
            name='property',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='houses', serialize=False, to='sellerapp.property'),
        ),
        migrations.AddField(
            model_name='villa',
            name='property',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='villas', serialize=False, to='sellerapp.property'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='sellerapp.property'),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='sellerapp.property'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='property_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='sellerapp.property'),
        ),
    ]
