# Generated by Django 4.2.6 on 2024-01-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0003_apartment_property_house_property_villa_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='property',
        ),
        migrations.RemoveField(
            model_name='house',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='property',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='property_ptr',
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('1BHK', '1 Bedroom, Hall, Kitchen, 1 Car Parking'), ('2BHK', '2 Bedrooms, Hall, Kitchen, 1 Car Parking'), ('3BHK', '3 Bedrooms, 2 Hall, Kitchen, 2 Car Parking'), ('4BHK', '4 Bedrooms, 2 Hall, 2 Kitchen, 3 Car Parking'), ('5BHK', '5 Bedrooms, 2 Hall, 2 Kitchen, 4 Car Parking')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Villa',
        ),
    ]
