# Generated by Django 4.2.6 on 2024-01-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0004_remove_house_property_remove_house_property_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Rate',
            new_name='rate',
        ),
    ]
