# Generated by Django 4.2.6 on 2024-01-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0005_rename_rate_property_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
