# Generated by Django 4.2.6 on 2024-01-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('trivandrum ', 'trivandrum city , nedumangad , kazhakkoottam ,attingal'), ('kollam', 'kollam , ayoor , anchal , kadakkal'), ('Alappuzha', 'cherthala , harippad , mavelikkara , kayamkulam , ambalapuzha, aroor '), ('ernakulam', 'kochi , paravur , aluva , kanayannor , muvattupuzha , kothamangalam '), ('kozhikode', 'calicut ,vatakara , koyilandy , thamarassery '), ('kasargod', 'kasargod , hosdurg , vellarikkund , manajeshwaram '), ('idukki', 'idukkic, devikulam , udumbanchola , thodupuzha , peerumade')]),
        ),
    ]
