# Generated by Django 4.2.6 on 2024-01-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0007_alter_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('trivandrum ', 'trivandrum city , nedumangad , kazhakkoottam ,attingal'), ('kollam', 'kollam , ayoor , anchal , kadakkal'), ('Alappuzha', 'cherthala , harippad , mavelikkara , kayamkulam , ambalapuzha, aroor '), ('ernakulam', 'kochi , paravur , aluva , kanayannor , muvattupuzha , kothamangalam '), ('kozhikode', 'calicut ,vatakara , koyilandy , thamarassery '), ('kasargod', 'kasargod , hosdurg , vellarikkund , manajeshwaram '), ('idukki', 'idukki, devikulam , udumbanchola , thodupuzha , peerumade')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='rate',
            field=models.CharField(choices=[('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('900', '900'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '5000'), ('6000', '6000'), ('7000', '7000'), ('8000', '8000'), ('9000', '9000'), ('10000', '10000'), ('15000', '15000')]),
        ),
    ]
