# Generated by Django 4.2.6 on 2024-01-10 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticationapp', '0003_alter_profile_contactno'),
        ('sellerapp', '0005_rename_rate_property_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('bookfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerapp.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticationapp.profile')),
            ],
        ),
    ]
