# Generated by Django 4.2.6 on 2024-01-09 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fullname', models.CharField(max_length=255)),
                ('contactno', models.IntegerField()),
                ('address', models.TextField()),
                ('documents', models.ImageField(upload_to='documents_details/')),
            ],
        ),
    ]
