# Generated by Django 4.2.6 on 2024-01-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='documents',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
