# Generated by Django 4.2.6 on 2024-01-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0002_alter_profile_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contactno',
            field=models.BigIntegerField(),
        ),
    ]
